repos:
-   repo: local
    hooks:
    -   id: isort
        name: Sorting Imports
        entry: isort
        language: system
        args: ["-y"]
        files: \.py$
        exclude: (.*/migrations/.*)$
        requirements: true
